name: Fetch YouTube Data

on:
  schedule:
    - cron: "0 0 * * *"   # midnight UTC
  workflow_dispatch:       # manual trigger allowed

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allow push commits

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run fetch script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python fetch_youtube.py

      - name: Commit & push updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add apple_youtube.csv backups/
          git commit -m "Update YouTube data ($(date -u))" || echo "No changes"
          git push
